// Property Data
const properties = [
  {
    id: "1",
    title: "Luxury Beachfront Villa",
    location: "Malibu, California",
    price: 350,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "Villa",
    rating: 4.9,
    reviewCount: 128,
    isFeatured: true,
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    size: "2,500 sq ft",
    description: "This beautiful villa offers stunning ocean views and modern amenities. Perfect for a relaxing beach getaway or a special celebration with friends and family. Enjoy the private pool, spacious deck, and direct beach access.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Washer", "Free parking", "Pool", "TV", "Workspace"]
  },
  {
    id: "2",
    title: "Modern Downtown Apartment",
    location: "New York City, NY",
    price: 120,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "Apartment",
    rating: 4.7,
    reviewCount: 85,
    isFeatured: false,
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    size: "750 sq ft",
    description: "This stylish apartment in the heart of Manhattan puts you within walking distance of major attractions, restaurants, and shops. Enjoy high ceilings, modern furnishings, and all the amenities you need for a comfortable stay.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Washer", "TV", "Workspace"]
  },
  {
    id: "3",
    title: "Seaside Family Home",
    location: "Santorini, Greece",
    price: 275,
    image: "https://images.unsplash.com/photo-1527517363811-5faf4e449c2f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "House",
    rating: 4.9,
    reviewCount: 97,
    isFeatured: true,
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    size: "1,200 sq ft",
    description: "This beautiful house offers stunning views and modern amenities. Perfect for a relaxing getaway or an exciting urban adventure. Enjoy spacious rooms, state-of-the-art facilities, and a prime location close to local attractions.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Washer", "Free parking", "Pool", "TV", "Workspace"]
  },
  {
    id: "4",
    title: "Cozy Mountain Cabin",
    location: "Aspen, Colorado",
    price: 195,
    image: "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "Cabin",
    rating: 4.8,
    reviewCount: 64,
    isFeatured: false,
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    size: "900 sq ft",
    description: "Escape to this charming cabin in the mountains. Perfect for nature lovers looking to hike, ski, or simply relax by the fireplace. The cabin features rustic decor with modern comforts and beautiful mountain views.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Free parking", "TV", "Workspace"]
  },
  {
    id: "5",
    title: "Urban Loft in Historic District",
    location: "Barcelona, Spain",
    price: 145,
    image: "https://images.unsplash.com/photo-1504494683949-7319a9ba12d1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "Loft",
    rating: 4.6,
    reviewCount: 42,
    isFeatured: false,
    bedrooms: 1,
    bathrooms: 1,
    guests: 3,
    size: "850 sq ft",
    description: "This stylish loft in Barcelona's historic quarter features high ceilings, exposed brick walls, and modern furnishings. Walk to major attractions, restaurants, and markets from this perfectly situated urban retreat.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Washer", "TV", "Workspace"]
  },
  {
    id: "6",
    title: "Lakeside Cottage with Boat Dock",
    location: "Lake Tahoe, CA",
    price: 230,
    image: "https://images.unsplash.com/photo-1475087542963-13ab5e611954?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "Cottage",
    rating: 4.8,
    reviewCount: 57,
    isFeatured: false,
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    size: "1,400 sq ft",
    description: "This charming lakeside cottage offers direct access to the crystal-clear waters of Lake Tahoe. Enjoy your private dock, outdoor fire pit, and stunning lake views. Perfect for families looking for a memorable vacation.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Washer", "Free parking", "TV", "Workspace"]
  },
  {
    id: "7",
    title: "Tropical Beachfront Bungalow",
    location: "Kauai, Hawaii",
    price: 310,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "Bungalow",
    rating: 4.9,
    reviewCount: 112,
    isFeatured: true,
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    size: "1,050 sq ft",
    description: "Experience Hawaii from this private beachfront bungalow. Fall asleep to the sound of ocean waves, wake up to stunning sunrises, and step directly onto the sand from your lanai. Perfect for couples or small families seeking paradise.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Free parking", "TV", "Workspace"]
  },
  {
    id: "8",
    title: "Historic Downtown Brownstone",
    location: "Boston, MA",
    price: 185,
    image: "https://images.unsplash.com/photo-1558442074-b427cfc18faa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "House",
    rating: 4.7,
    reviewCount: 73,
    isFeatured: false,
    bedrooms: 3,
    bathrooms: 2.5,
    guests: 6,
    size: "1,800 sq ft",
    description: "Stay in a piece of history in this beautifully restored brownstone in Boston's historic downtown. Featuring elegant details, modern updates, and a private garden, this home puts you steps away from the Freedom Trail and top city attractions.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Washer", "TV", "Workspace"]
  },
  {
    id: "9",
    title: "Minimalist Studio in Arts District",
    location: "Berlin, Germany",
    price: 95,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    type: "Studio",
    rating: 4.5,
    reviewCount: 38,
    isFeatured: false,
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    size: "550 sq ft",
    description: "This sleek, minimalist studio in Berlin's trendy Arts District is the perfect home base for exploring the city's rich culture. The open-concept space features designer furnishings, large windows, and all essential amenities.",
    amenities: ["Wi-Fi", "Air conditioning", "Kitchen", "Washer", "TV", "Workspace"]
  }
];

// Popular Locations Data
const locations = [
  {
    name: "Paris, France",
    slug: "paris",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    propertyCount: 843
  },
  {
    name: "Bali, Indonesia",
    slug: "bali",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    propertyCount: 621
  },
  {
    name: "New York, USA",
    slug: "new-york",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    propertyCount: 932
  },
  {
    name: "Tokyo, Japan",
    slug: "tokyo",
    image: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    propertyCount: 512
  }
];